name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --tag eoluchile/ecommerce-webpay:${GITHUB_SHA}

      - name: Push to Github Container Registry
        run: |
          echo "${CR_PAT}" | docker login ghcr.io -u eolito --password-stdin
          docker tag eoluchile/ecommerce-webpay:${GITHUB_SHA} ghcr.io/eol-uchile/ecommerce-webpay:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/ecommerce-webpay:${GITHUB_SHA}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}